### ISSUE TITLE
geom_bar behaves different as that of R

### ISSUE THREAD

**Issue by lucidfrontier45** [yhat/ggplot#373]
Hi all.

I have those R and python `geom_bar` codes which should be the same.
However they are different as you can see.
While R's ggplot fig is what I expected, python's ggplot gives a stacked one.
How can I get equivalent fig to R?

My env is

- python(2.7.8, anaconda), ggplot(0.6.5), matplotlib(1.3.1)
- R (3.1.1), ggplot2(1.0.0)

Thank you.

R
==

```R
idx = c(1,2,3)
numbers = c(100, 70, 300)
df = data.frame(idx, numbers)
ggplot(aes(x=factor(idx), y=numbers, fill=factor(idx)), data=df) + geom_bar(stat='identity')
```
![r](https://cloud.githubusercontent.com/assets/655305/4442534/0beba348-47e0-11e4-8826-2b2d985d0680.png)

Python
==

```python
import numpy as np
import pandas as pd
from ggplot import *

idx = [1,2,3]
numbers = [100, 70, 300]
df = pd.DataFrame({"idx":idx, "numbers":numbers})

ggplot(aes("factor(idx)", "numbers", fill="factor(idx)"), df) + geom_bar(stat="identity")
```
![python](https://cloud.githubusercontent.com/assets/655305/4442552/3cbb6d28-47e0-11e4-850b-db1b2091b712.png)

**Comment by glamp** [comment]
![image](https://cloud.githubusercontent.com/assets/1409333/15691880/43f34246-2759-11e6-9ef8-94931a149e55.png)
`ggplot(aes(x="factor(idx)", weight="numbers", fill="factor(idx)"), df) + geom_bar(stat="identity")`

**Comment by edlee123** [comment]
Running  ggplot==0.11.5 via: 
"conda install -c conda-forge ggplot"  on python 3.5

Trying to produce stacked bar charts like the code (2 posts above):
```
import numpy as np
import pandas as pd
from ggplot import *

idx = [1,2,3]
numbers = [100, 70, 300]
df = pd.DataFrame({"idx":idx, "numbers":numbers})

ggplot(aes("factor(idx)", "numbers", fill="factor(idx)"), df) + geom_bar(stat="identity")
```

I get the attached:
![screenshot at 2017-01-16 17-10-20](https://cloud.githubusercontent.com/assets/16417837/22000708/b3893e98-dc0e-11e6-9ab5-0627d66a8a84.png)

Would be great if there were more stacked bar examples.  Did something change since that  post?

**Comment by jwhendy** [comment]
Coming from `R`, I also expected `y=foo` to work as long as `stat="identity"` was used.

In any case, good to know, but without `y=foo`, I don't get any label on the y-axis. That's the case with the [example used](https://github.com/yhat/ggpy/issues/373#issuecomment-222834004) to close this issue. Is that intentional?
