### ISSUE TITLE
Unrecognised backend

### ISSUE THREAD

**Issue by naught101** [yhat/ggplot#445]
When I try to import ggplot from within Spyder 3.0.0dev, I get an "unrecognised backend" error. This doesn't happen in ipython console, so it's possible it's a problem with Spyder. If so, let me know, and I'll repost the bug there.

```{python}
Python 3.4.3 |Continuum Analytics, Inc.| (default, Jun  4 2015, 15:29:08) 
Type "copyright", "credits" or "license" for more information.

IPython 3.2.1 -- An enhanced Interactive Python.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
%guiref   -> A brief reference about the graphical user interface.

In [1]: import ggplot
Traceback (most recent call last):

  File "<ipython-input-1-1140326dc452>", line 1, in <module>
    import ggplot

  File "/home/naught101/miniconda3/envs/science/lib/python3.4/site-packages/ggplot/__init__.py", line 14, in <module>
    _set_mpl_backend()

  File "/home/naught101/miniconda3/envs/science/lib/python3.4/site-packages/ggplot/__init__.py", line 12, in _set_mpl_backend
    mpl.use(env_backend)

  File "/home/naught101/miniconda3/envs/science/lib/python3.4/site-packages/matplotlib/__init__.py", line 1312, in use
    name = validate_backend(arg)

  File "/home/naught101/miniconda3/envs/science/lib/python3.4/site-packages/matplotlib/rcsetup.py", line 161, in validate_backend
    return _validate_standard_backends(s)

  File "/home/naught101/miniconda3/envs/science/lib/python3.4/site-packages/matplotlib/rcsetup.py", line 60, in __call__
    % (self.key, s, list(six.itervalues(self.valid))))

ValueError: Unrecognized backend string "automatic": valid strings are ['nbAgg', 'GTK', 'GTK3Cairo', 'emf', 'CocoaAgg', 'WXAgg', 'agg', 'GTKCairo', 'GTKAgg', 'WebAgg', 'pgf', 'Qt5Agg', 'Qt4Agg', 'TkAgg', 'pdf', 'cairo', 'GTK3Agg', 'svg', 'ps', 'WX', 'MacOSX', 'template', 'gdk']
```

**Comment by JanSchulz** [comment]
@yarikoptic can you look at this, the code is from you (https://github.com/yhat/ggplot/commit/7c09414ffa84f71793379f9a73ddb5a8b08c9c28) :-)

I tried to find out if matplotlib recognises this environment variable (`MATPLOTLIB_BACKEND`), but it seems it does not? http://matplotlib.org/faq/environment_variables_faq.html does not list such a env var... It does recognise `MPLBACKEND` (https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/__init__.py#L1399)

Reading this (https://github.com/spyder-ide/spyder/blob/master/spyderlib/widgets/externalshell/sitecustomize.py#L311), it seems that spyder uses that env variable to let a user costumize the backend and it's set via spyder settings. If that's so, we can do two things:

* throw this bug back at the spyder devs so that they remove the env var before starting up the python kernel (cc: @ccordoba12)
* we recognize the problematic variable values and filter them out here: https://github.com/yhat/ggplot/blob/master/ggplot/__init__.py#L10

Anyway: the workround is probably to explicitly set the matplotlib backend somewhere in the spyder settings.

**Comment by ccordoba12** [comment]
Thanks @JanSchulz for pinging me about this bug. It seems the problem is `ggplot` uses `MATPLOTLIB_BACKEND` to get a backend name from the environment.

We use that same variable in Spyder to pass the name set by the user through our Preferences dialog to the external process which runs a Python/IPython console. I decided to add `Automatic` as a possible backend, so that we can configure the right backend for our users without them needing to know its exact name.

The solution then is easy: change that variable in the Spyder side to avoid a clash with `ggplot`. I'll do it in a couple of days. :-)

**Comment by yarikoptic** [comment]
Hi guys, sorry for a delay with the follow up.  Treatment of MATPLOTLIB_BACKEND was introduced indeed by me in https://github.com/yhat/ggplot/pull/35.  And why I chose that variable is that I was not aware that matplotlib finally introduced recognition of env variables.  Please do whatever you feel necessary/best if you would like to change the name etc ;)

**Comment by ccordoba12** [comment]
@yarikoptic, that's not a variable used by Matplotlib. It just happens that both you and me (in `ggplot` and `spyder`, respectively) decided to use the same env variable name, and now they clash ;-)

Since our use is particular to Spyder (because one value of that variable can be `automatic` for us), I'll change its name in Spyder, and that should solve this issue :-)

**Comment by JanSchulz** [comment]
We should probably also change it to something like `GGPLOT_MATPLOT_BACKEND`... :-)

**Comment by ccordoba12** [comment]
Ok, I fixed this problem in Spyder master. @naught101, please update :-)

**Comment by naught101** [comment]
Yas! Works! thanks :)
